### ISSUE TITLE
Tauren start zone time waste

### ISSUE THREAD

**Issue by dh-mmo** [EchoTiger/NewQuestingPack#31]
My lvl 6 went from mulgore to start camp to vendor items

**Comment by EchoTiger** [comment]
The vendor data for Mulgore is missing, which is causing the bot to resort to the vendor database.

In this situation, the vendor database is determining that the vendors at the starting zone would be a better option to go to rather than the vendors in Bloodhoof Village.

In commit https://github.com/EchoTiger/NewQuestingPack/commit/ab328d741c47793f8867896031665b28ce8377aa I've added some vendor data which should prevent this issue from happening.
