### ISSUE TITLE
Quest 26028 doesnt really work

### ISSUE THREAD

**Issue by dh-mmo** [EchoTiger/NewQuestingPack#33]
https://puu.sh/wbPCm/129a7004f6.png

bot stands here till low life...then kills mobs...waits again. walks to another group...kills them...waits for respawn on the same spot...close to die
"you cannot do this" - red message

[3404 2017-06-05 16.18.txt](https://github.com/EchoTiger/NewQuestingPack/files/1052954/3404.2017-06-05.16.18.txt)

after the vehicle dies, he runs through all mobs without combat and trys to kill mobs

works after stop/start

**Comment by EchoTiger** [comment]
For some reason your bot enabled combat while doing this quest which makes no sense at all especially considering there's nothing in the log that shows combat was enabled.

Right now the code for handling this quest operates on a "Questbot_Profile" level.
I've elevated it to a "Questbot_Main" level so that it can run over all the other bot logics without relying on disable codes - this change is in commit 
https://github.com/EchoTiger/NewQuestingPack/commit/46f1188ad98ad9e11de58c7dbb30aa4297a86dd1
