### ISSUE TITLE
LvL 62 - Zangar marsh

### ISSUE THREAD

**Issue by dh-mmo** [EchoTiger/NewQuestingPack#39]
toon is swimming arround, doing nothing.
[6548 2017-06-07 09.19.txt](https://github.com/EchoTiger/NewQuestingPack/files/1057174/6548.2017-06-07.09.19.txt)
![vmware_2017-06-07_09-27-12](https://user-images.githubusercontent.com/28988584/26866942-a9b14d10-4b63-11e7-8983-eaedf8b4e3df.png)

he doesnt have the quest hes actualy trying to do.
/run print(IsQuestFlaggedCompleted(9720))
> false

he didnt do the quest chain before:
http://de.wowhead.com/quest=9716/anomalie-am-umbrafennsee
http://de.wowhead.com/quest=9718/der-flug-der-krahe

**Comment by nahhets** [comment]
Stupid place and part. Most time on my all bots at this point bags are full. You need forcing DoVendor by hand.

**Solution is add code for buying 4x bags from vendor in Town before coming to Outland. Gold is enough at this level.** http://wowhead.com/item=60335

**Comment by dh-mmo** [comment]
nope was not related to full bags

**Comment by EchoTiger** [comment]
This is related to full bags - the error in your log is that the bot is trying to vendor to a NPC which is located under the lake.  The NPC is: http://www.wowhead.com/npc=23373/mortog-steamhead
Since he is under ground, the bot is having navigation issues getting to him which is causing it to fly into the lake.

This was fixed on the Alliance version of the profiles by me manually adding vendor data overrides to the profile so it ignores using Mortog as a vendor.

The Horde profile still lacks the vendor data, which is causing the issue.
Fixed in https://github.com/EchoTiger/NewQuestingPack/commit/e8f934d7f11c46936e29b251c8bd4100f9d021c6
