### ISSUE TITLE
lvl 99 dowhen bug

### ISSUE THREAD

**Issue by dh-mmo** [EchoTiger/NewQuestingPack#46]
[2552 2017-06-09 05.23.txt](https://github.com/EchoTiger/NewQuestingPack/files/1063746/2552.2017-06-09.05.23.txt)

happens most time, when hes unter some stairs and mounting fails because the is to big to mount up.
it also looks weird, goes into cat form, mounts up, rides, cat form, mounts up...and so on

**Comment by EchoTiger** [comment]
Fixed in https://github.com/EchoTiger/NewQuestingPack/commit/9d0f4f1c29565bdd1250c86b4aa59bf724e4baeb

Disabled combat mount usage for Druids (since they have Travel Form and it's almost the same) and set the code so it only runs every 5seconds rather than instantly. 
That way if the bot is under stairs and it fails to mount,  it will wait 5 more seconds before attempting again.
