### ISSUE TITLE
Char is moving "crazy"   in Grizzly Hills  .. RareKiller/Chest Grabber issue

### ISSUE THREAD

**Issue by marrvin2** [EchoTiger/NewQuestingPack#51]
From what I saw, there was  a Rare and a Chest nearby.
The char did some crazy random moves....looks like he gets multiple different   "movement" orders 
[3756 2017-06-20 08.53.txt.zip](https://github.com/EchoTiger/NewQuestingPack/files/1087349/3756.2017-06-20.08.53.txt.zip)

**Comment by EchoTiger** [comment]
I've seen this on my testers and current I'm working on it.

**Comment by EchoTiger** [comment]
This may have been fixed in my https://github.com/EchoTiger/NewQuestingPack/commit/fe8259be1f7bdd42c76259abfbbcef55853e022e commit as I just noticed this on a tester earlier.

The rare hunter logic is trying to engage a mob that's blacklisted, so it's bouncing between trying to "trying to kill" and "clearing kill" logics.

The commit I linked above adds a blacklist check so it won't do this.

There's still more improvements to the Rare Hunter logic that is needed - but for now this specific issue should be fixed.
