### ISSUE TITLE
Goal: Picking up quest with ID A Sort Of Homecoming [Ref: "Pickup" @line 495]

### ISSUE THREAD

**Issue by VoidtechX** [EchoTiger/NewQuestingPack#8]
DK start area, bot unable to pick up quest from Knight Commander Plaguefist
[10884 2017-05-19 02.49.txt](https://github.com/EchoTiger/NewQuestingPack/files/1012800/10884.2017-05-19.02.49.txt)

**Comment by EchoTiger** [comment]
Do you recall what was happening when it failed to pick the quest up?
Was there a quest frame opened and bugged out on the interface?

**Comment by VoidtechX** [comment]
It's not the frame bug, bot should firstly pick up quest "http://www.wowhead.com/quest=12748/a-special-surprise" but is trying to get next quest

**Comment by EchoTiger** [comment]
I can't tell what version of the profile you're using, but there was a very short time that the Horde Death Knight profile didn't have proper handling of the quest:  "A Special Surpise"  because this quest changes depending on which race you are.

Code for this quest was added a while back though.
http://azyul.com/l/14-34-49.jpg

I'm going to assume you had the bad version of the profile since this was fixed previously.
